### ISSUE TITLE
digsec-0.6 installation issue

### ISSUE THREAD

**Issue by markdevil87** [metebalci/digsec#1]
Hi, I'm trying to install digsec-0.6 with pip and I get this error:

`$ pip install digsec
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting digsec
  Using cached digsec-0.6.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uakLGm/digsec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uakLGm/digsec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-WD63ZX
         cwd: /tmp/pip-install-uakLGm/digsec/
    Complete output (23 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uakLGm/digsec/setup.py", line 3, in <module>
        setup()
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 705, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 120, in parse_configuration
        meta.parse()
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 425, in parse
        section_parser_method(section_options)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 398, in parse_section
        self[name] = value
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 183, in __setitem__
        value = parser(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 513, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 349, in _parse_attr
        value = getattr(module, attr_name)
    AttributeError: 'module' object has no attribute 'DIGSEC_VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Am I wrong?

Thanks in advance.

**Comment by vituc01** [comment]
Try installing python3

**Comment by metebalci** [comment]
digsec requires Python 3
